# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: employer.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'employer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65mployer.proto\x12\x08\x65mployer\"+\n\x0f\x45mployerRequest\x12\x18\n\x10maticna_stevilka\x18\x01 \x01(\t\"\xf6\x01\n\x08\x45mployer\x12\x18\n\x10maticna_stevilka\x18\x01 \x01(\t\x12\x13\n\x0bpopolno_ime\x18\x02 \x01(\t\x12\r\n\x05hseid\x18\x03 \x01(\t\x12\x15\n\rpravna_oblika\x18\x04 \x01(\t\x12\x18\n\x10registrski_organ\x18\x05 \x01(\t\x12\r\n\x05ulica\x18\x06 \x01(\t\x12\x10\n\x08hisna_st\x18\x07 \x01(\t\x12\x18\n\x10hisna_st_dodatek\x18\x08 \x01(\t\x12\x0f\n\x07naselje\x18\t \x01(\t\x12\x10\n\x08posta_st\x18\n \x01(\t\x12\r\n\x05posta\x18\x0b \x01(\t\x12\x0e\n\x06\x64rzava\x18\x0c \x01(\t\"6\n\x10\x45mployerResponse\x12\"\n\x06result\x18\x01 \x03(\x0b\x32\x12.employer.Employer2X\n\x0f\x45mployerService\x12\x45\n\x0cGetByMaticna\x12\x19.employer.EmployerRequest\x1a\x1a.employer.EmployerResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'employer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPLOYERREQUEST']._serialized_start=28
  _globals['_EMPLOYERREQUEST']._serialized_end=71
  _globals['_EMPLOYER']._serialized_start=74
  _globals['_EMPLOYER']._serialized_end=320
  _globals['_EMPLOYERRESPONSE']._serialized_start=322
  _globals['_EMPLOYERRESPONSE']._serialized_end=376
  _globals['_EMPLOYERSERVICE']._serialized_start=378
  _globals['_EMPLOYERSERVICE']._serialized_end=466
# @@protoc_insertion_point(module_scope)
