spring.application.name=hub
spring.r2dbc.url=${DB_URL}

spring.sql.init.mode=never

pdf-generator.base-url=${PDF_GENERATOR_URL:http://localhost:3001}

jwt.secret=${JWT_SECRET}

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
